version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - foodienet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - foodienet

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sbRAcyuDgQVRPHqOwFSBGONhbqmLooFV
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_HOST: interchange.proxy.rlwy.net
      MYSQL_PASSWORD: sbRAcyuDgQVRPHqOwFSBGONhbqmLooFV
    ports:
      - "51103:51103"
    networks:
      - foodienet
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/foodiefiesta.sql:/docker-entrypoint-initdb.d/foodieFiesta.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  foodienet:

volumes:
  mysql_data: